"""change salary column name to pay

Revision ID: 3e561c865903
Revises: d3aa4bc3265c
Create Date: 2024-04-03 12:15:03.317978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e561c865903'
down_revision = 'd3aa4bc3265c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay', sa.Float(), nullable=False))
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.FLOAT(), nullable=False))
        batch_op.drop_column('pay')

    # ### end Alembic commands ###
