"""change a table name from favorites to favorite_jobs

Revision ID: 4a70c1586f4f
Revises: 0da103d7f95e
Create Date: 2024-04-04 11:15:28.600337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a70c1586f4f'
down_revision = '0da103d7f95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_favorite_jobs_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_favorite_jobs_job_posting_id_job_postings')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), nullable=True),
    sa.Column('Job_posting_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['Job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name='fk_favorites_applicant_id_applicants'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_jobs')
    # ### end Alembic commands ###
