"""add applicants and job_applications table

Revision ID: d3aa4bc3265c
Revises: 7dcc42c4e33f
Create Date: 2024-03-27 12:22:42.779374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3aa4bc3265c'
down_revision = '7dcc42c4e33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('certificate', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_job_applications_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_job_applications_job_posting_id_job_postings')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_applicant_id_applicants'), 'applicants', ['applicant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_applicant_id_applicants'), type_='foreignkey')
        batch_op.drop_column('applicant_id')

    op.drop_table('job_applications')
    op.drop_table('applicants')
    # ### end Alembic commands ###
